USE [INFORMESPOS]
GO

/**
   PROGRAMA: PRC_CODIGOS_MP_DIAN
   AUTOR: HUGO CASTAÑEDA
   FECHA: 2022-09-06
   PROPOSITO: RECIBE COMO PARAMETRO UN CODIGO DE MEDIO DE PAGO POS Y DEVUELVE EL EQUIVALENTE DIAN
   MODIFICACIONES:

   EXEC PRC_CODIGOS_MP_DIAN '17'
**/

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[PRC_CODIGOS_MP_DIAN]
@ID_MEDIO VARCHAR(2)

AS

IF(SELECT COUNT(1) FROM MEDIOS_DE_PAGO WHERE TIPOVARIEDAD=@ID_MEDIO)=0
BEGIN
   SELECT D.CODIGO,D.DESCRIPCION FROM "dbo"."DIANPaymentMeansCode" D
   WHERE D.CODIGO='ZZZ'
   RETURN
END

SELECT D.CODIGO,D.DESCRIPCION FROM "dbo"."DIANPaymentMeansCode" D 
INNER JOIN MEDIOS_DE_PAGO M ON D.CODIGO = M.CODIGO_DIAN
WHERE M.TIPOVARIEDAD = @ID_MEDIO

RETURN

GO


