USE [INFORMESPOS]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author, HUGO CASTAÑEDA>
-- Create date: <Create Date, 16/09/2022>
-- Description:	<Description, VALIDA SI EL CLIENTE ES APTO PARA F.E.>
-- =============================================
-- EXECUTE PRC_FACTURA_ELECTRONICA_CLIENTE_APTO '71746198', '01', '01'
-- EXECUTE PRC_FACTURA_ELECTRONICA_CLIENTE_APTO '39207079', '01', '01'

CREATE PROCEDURE [dbo].[PRC_FACTURA_ELECTRONICA_CLIENTE_APTO]
	@DOCUMENTO VARCHAR(20),
	@TIENDA VARCHAR(5),
	@CAJA VARCHAR(4)
AS
BEGIN
	IF (SELECT DISTINCT 1 FROM BI.CLIENTESBI WHERE CEDULA = @DOCUMENTO) = 1
	BEGIN
		SELECT @DOCUMENTO + ': APTO F.E.'
	END
	ELSE
	BEGIN
		IF (SELECT DISTINCT 1 FROM TFE_TEMP_CLIENTES_NUEVOS WHERE NUMERO_DOCUMENTO = @DOCUMENTO) = 1
		BEGIN
			SELECT @DOCUMENTO + ': APTO F.E.'
		END
		ELSE
		BEGIN
			SELECT @DOCUMENTO + ': NO APTO F.E.'
		END
	END
END	